services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
  postgres:
    container_name: db
    image: postgres:16
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
volumes:
  postgres:
  redis:
